name: Axiomcore-SYSTEM
version: 1.0.0
description: AxiomCore MVP — backend, frontend, AI orchestration

metadata:
  platform: AxiomCore
  type: mvp
  license: MIT
  organization: TechFusion-Quantum-Global-Platform
  repository: https://github.com/FARICJH59/README-.gitignore-license
  actualRepository: https://github.com/TechFusion-Quantum-Global-Platform/Axiomcore-SYSTEM
  visibility: private
  maintainers:
    - FARICJH59
    - AxiomCore Team
  contact:
    email: farichva@gmail.com
    owner: FARICJH59
  compliance:
    codeowners: .github/CODEOWNERS
    securityPolicy: SECURITY.md
    contributingGuide: CONTRIBUTING.md
    dependabot: .github/dependabot.yml

configuration:
  runtime:
    engine: PowerShell
    version: 7.0+
    pythonVersion: 3.8+
  
  providers:
    enabled:
      - aws
      - gcp
      - azure
      - nvidia
      - local
    default: local

  orchestration:
    engine: UDO
    dagEnabled: true
    maxConcurrentJobs: 10
    retryPolicy:
      maxAttempts: 3
      backoff: exponential

  api:
    enabled: true
    port: 8080
    authentication: jwt
    rateLimit:
      enabled: true
      requestsPerMinute: 100

  telemetry:
    enabled: true
    eventBus: true
    metricsCollectionInterval: 60s
    loggingLevel: info

  governance:
    enabled: true
    complianceMode: strict
    auditLogging: true
    codeReview:
      required: true
      minApprovals: 1
      dismissStaleReviews: true
      requireCodeOwners: true
    branchProtection:
      main:
        requirePullRequest: true
        requireApprovals: 1
        requireStatusChecks: true
        requireUpToDate: true
        enforceAdmins: false
    securityScanning:
      secretScanning: true
      dependabotAlerts: true
      dependabotSecurityUpdates: true
      codeScanning: true

  ai:
    enabled: true
    supportedFrameworks:
      - tensorflow
      - pytorch
      - onnx
    defaultRuntime: cpu

components:
  - name: runtime
    path: ./runtime
    type: core
    
  - name: providers
    path: ./providers
    type: integration
    
  - name: orchestrator
    path: ./orchestrator
    type: core
    
  - name: api
    path: ./api
    type: service
    
  - name: ai
    path: ./ai
    type: service
    
  - name: governance
    path: ./governance
    type: service
    
  - name: telemetry
    path: ./telemetry
    type: service
    
  - name: registry
    path: ./registry
    type: core

profiles:
  development:
    provider: local
    debug: true
    hotReload: true
    
  staging:
    provider: aws
    region: us-east-1
    
  production:
    provider: aws
    region: us-west-2
    highAvailability: true
    backupEnabled: true

dependencies:
  powershell:
    - PSScriptAnalyzer
    - Pester
    
  python:
    - requests
    - pyyaml
    - click

build:
  steps:
    - validate
    - test
    - package
  
  validation:
    scripts: true
    configuration: true
    
  testing:
    unit: true
    integration: true
    coverage: 80%

deployment:
  strategy: rolling
  healthCheck:
    enabled: true
    path: /health
    interval: 30s
  
  rollback:
    automatic: true
    threshold: 5%
